extends RefCounted


func run(t: TestHarness, host: Node) -> void:
	t.suite("burst node reuse")
	var world := Node3D.new()
	host.add_child(world)
	var first := MeshFactory.burst(Color.RED, 4, 2.0, 0.5)
	world.add_child(first)
	first.set_process(false)
	var root_id := first.get_instance_id()
	var shard_id: int = first._shards[0].get_instance_id()
	first._process(0.6)
	t.ok(not first.is_queued_for_deletion(), "expired burst retains a reusable root")
	t.ok(not first.visible, "expired burst is not visible while idle")
	var next := MeshFactory.burst(Color.BLUE, 3, 1.0, 0.4)
	world.add_child(next)
	next.set_process(false)
	t.equal(next.get_instance_id(), root_id, "next burst reuses the expired root")
	t.equal(next._shards[0].get_instance_id(), shard_id, "next burst reuses existing shard nodes")
	t.equal(next._age, 0.0, "reuse resets elapsed life")
	t.equal(next.transform, Transform3D.IDENTITY, "reuse resets root transforms")
	t.equal(next._active_count, 3, "reuse resets active shard count")
	t.equal(next._velocities.size(), 3, "reuse discards preceding velocities")
	t.equal(next._shards.size(), 4, "smaller effects retain reusable spare shards")
	t.ok(not next._shards[3].visible, "unused spare shards are hidden")
	t.equal(next._shards[0].material_override.albedo_color, Color.BLUE, "reuse updates the visible material colour")
	next._process(0.1)
	t.ok(next._shards[0].position != Vector3.ZERO, "reused shards still animate")
	next._process(0.5)
	next._process(0.5)
	t.equal(Pool.stats().fx_burst.free, 1, "idle retirement cannot insert the same root twice")
	var other_world := Node3D.new()
	host.add_child(other_world)
	var moved := MeshFactory.burst(Color.GREEN, 6, 3.0, 1.0)
	other_world.add_child(moved)
	moved.set_process(false)
	t.equal(moved.get_instance_id(), root_id, "reuse can move a visual-only burst to another parent")
	t.equal(moved._shards[0].transform, Transform3D.IDENTITY, "reuse removes stale shard scale and rotation")
	t.equal(moved._shards.size(), 6, "larger effects grow the shard bank only as needed")
	var simultaneous: Array[Node3D] = []
	var ids := {}
	for index in 12:
		var effect := MeshFactory.burst(Color.YELLOW, 2, 1.0, 0.2)
		world.add_child(effect)
		effect.set_process(false)
		ids[effect.get_instance_id()] = true
		simultaneous.append(effect)
	t.equal(ids.size(), 12, "concurrent effects never check out the same root")
	t.equal(Pool.stats().fx_burst.live, 13, "pool tracks all concurrent bursts")
	for effect in simultaneous:
		effect._process(0.3)
	t.equal(Pool.stats().fx_burst.free, 8, "idle retention is bounded to eight roots")
	t.equal(Pool.stats().fx_burst.live, 1, "discarding idle overflow preserves live bookkeeping")
	for index in range(8, 12):
		t.ok(simultaneous[index].is_queued_for_deletion(), "overflow roots retire rather than accumulate")
	Pool.trim_idle()
	t.equal(Pool.stats().fx_burst.free, 0, "memory pressure releases idle burst geometry")
	t.equal(Pool.stats().fx_burst.live, 1, "memory pressure preserves the active burst")
	t.ok(Pool.has_pool("fx_burst"), "memory pressure preserves the burst factory")
	t.ok(not moved.is_queued_for_deletion(), "memory pressure does not remove active visual effects")
	moved._process(1.1)
	t.equal(Pool.stats().fx_burst.free, 1, "active effects can return after memory pressure")
	var large := MeshFactory.burst(Color.WHITE, 40, 1.0, 0.1)
	world.add_child(large)
	large.set_process(false)
	t.equal(large._shards.size(), 40, "large authored effects retain their full count")
	large._process(0.2)
	t.ok(large.is_queued_for_deletion(), "large effects do not enlarge idle shard budgets")
	Pool.drain("fx_burst")
	t.ok(not Pool.has_pool("fx_burst"), "round teardown removes the burst factory")
	var fresh := MeshFactory.burst(Color.RED, 1, 1.0, 0.1)
	world.add_child(fresh)
	fresh.set_process(false)
	t.ok(fresh.get_instance_id() != root_id, "next round does not resurrect preceding roots")
	Pool.drain("fx_burst")
	fresh._process(0.2)
	t.ok(fresh.is_queued_for_deletion(), "active effect after teardown cannot recreate a dead pool")
	t.ok(not Pool.has_pool("fx_burst"), "late expiry leaves the torn-down pool absent")
	other_world.queue_free()
	world.queue_free()
	Pool.drain("fx_burst")
	await host.get_tree().process_frame
	MeshFactory.prepare_bursts([Color.RED, Color.BLUE] as Array[Color])
	t.equal(Pool.stats().fx_burst.free, 8, "preparation retains exactly the existing idle budget")
	MeshFactory.prepare_bursts([Color.GREEN] as Array[Color])
	t.equal(Pool.stats().fx_burst.free, 8, "repeated preparation cannot duplicate roots")
	var prepared: Array[Node3D] = []
	var shared_mesh: Mesh
	for index in 8:
		var effect := MeshFactory.burst(Color.RED, 7)
		world = Node3D.new()
		host.add_child(world)
		world.add_child(effect)
		prepared.append(world)
		t.equal(effect._shards.size(), 32, "first concurrent hits already own the bounded shard bank")
		for shard in effect._shards:
			if shared_mesh == null:
				shared_mesh = shard.mesh
			t.equal(shard.mesh, shared_mesh, "all burst shards reuse immutable geometry")
		t.equal(effect._active_count, 7, "preparation does not change authored hit count")
		t.equal(effect._shards[0].material_override.albedo_color, Color.RED, "prepared shards use actual effect color")
	t.equal(Pool.stats().fx_burst.live, 8, "prepared roots retain normal live bookkeeping")
	var reference := MeshFactory.box(Vector3.ONE * 0.16, Color.RED, 0.8)
	t.equal(shared_mesh.get_aabb(), reference.mesh.get_aabb(), "shared geometry preserves original shard bounds")
	t.equal(shared_mesh.surface_get_arrays(0), reference.mesh.surface_get_arrays(0), "shared geometry preserves original vertices and normals")
	reference.free()
	for parent in prepared:
		parent.get_child(0)._process(1.0)
	Pool.drain("fx_burst")
	for parent in prepared:
		parent.queue_free()
	await host.get_tree().process_frame
